// <auto-generated />
namespace ShapeShift.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig32));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251443076_mig32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
